import type { NextPage } from "next";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Nav from "../components/Nav";
import Router from "next/router";
import DashboardHome from "../components/DashboardHome";

const Home: NextPage = () => {
  // const { status, data } = useSession({
  //   required: true,
  //   onUnauthenticated() {
  //     Router.push("/login");
  //   },
  // });

  return (
    <>
      <Head>
        <title>Neutral Party</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className="h-18"></div>

      <DashboardHome />
    </>
  );
};

export default Home;
